config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'todos', to: 'todos#index'
get 'todos/list'
get 'todos/new'
post 'todos', to:'todos#create'
get 'todos/:id', to: 'todos#show', as:'todo'
get 'todos/:id/edit', to: 'todos#edit', as:'edit'
patch 'todos/:id', to: 'todos#update'
delete 'todos/:id', to: 'todos#destroy'
post 'todos/:id/complete', to: 'todos#complete', as: 'complete'
root 'todos#index'








end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.completed = false
        @todo.save
        redirect_to todos_path
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path

    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.delete
        redirect_to todos_path
    end

    def complete
        @todo = Todo.find(params[:id])
        @todo.completed = true
        @todo.save
        redirect_to todos_path

    end

    def list
        @todos = Todo.all
    end






    

    private

    def todo_params
        params.require(:todo).permit(:description, :completed)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:rgba(255,255,200,0.5);">

  <div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary sticky-top">
  <a class="navbar-brand" href="<%= todos_path %>">ToDo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= todos_path %>">Index <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%= todos_list_path %>">List</a>
      <a class="nav-item nav-link" href="<%= todos_new_path %>">Create ToDo</a>
      
    </div>
  </div>
</nav>



  <%= yield %>

  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  </body>


</html>

app/views/todos/edit.html.erb
<h1>EDITAR TAREA</h1>


<%= form_with(model: @todo, local: true) do |f|%>
<%= f.label :description, 'description' %>
<%= f.text_field :description %>
<%= f.label :completed,'check' %>
<%= f.check_box :completed %>

<%= f.submit :create %>
<% end %>

app/views/todos/index.html.erb
<h1>index</h1>
<%= link_to "create ToDo", todos_new_path  %>



<%= link_to "Listar",  todos_list_path %>


<% @todos.each do |todo| %>


<div class="card" style="width: 50rem;">
  <div class="card-body">
    <h5 class="card-title">DESCRIPCION TAREA</h5>
    <p class="card-text"><%= todo.description %></p>
    <p class="card-text"><%= todo.completed %></p>

    <div>

    <%= link_to 'completed', complete_path(todo), method: :complete, class: "btn btn-primary"  %>

    
    

    <%= link_to "Mostrar Tarea", todo, class:"btn btn-success"  %>
    

    <%= link_to "EDITAR TAREA", edit_path(todo), class:"btn btn-info"  %>

    <%= link_to "ELIMINAR TAREA", todo, method: :delete, class:"btn btn-danger" %>
   
    </div>


   
  </div>
</div>




    
    
<% end %>

app/views/todos/list.html.erb
<%= link_to "back", todos_path  %>




<div class="container">
  <div class="row">
        <div class="col-lg-6">
                <h1>COMPLETADO</h1>

                <% @todos.each do |todo| %>

                    <div>
                        <% if todo.completed %>

                        <%= todo.description %>
                        <%= todo.completed %>

                        <%end %>

                    </div>
                <%end %>
        </div>

                <div class="col-lg-6">

                <h1>NO COMPLETADO</h1>
                
                <% @todos.each do |todo| %>

                    <div>
                        <% if !todo.completed %>

                        <%= todo.description %>
                        <%= todo.completed %>

                        <%end %>
                    </div>
                <%end %>
        </div>

    </div>
</div>

app/views/todos/new.html.erb
<h1>CREAR NUEVA TAREA</h1>

<%= link_to "back", todos_path  %>


<%= form_with(model: @todo, local: true) do |f|%>
<%= f.label :description, 'Descripcion Tarea' %>
<%= f.text_field :description %>
<%= f.label :completed,'Check' %>
<%= f.check_box :completed %>

<%= f.submit :create %>
<% end %>

app/views/todos/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Descripcion Tarea</h5>
    <p class="card-text"><%= @todo.description %></p>
    <p class="card-text"><%= @todo.completed %></p>
  
    
<%= link_to "REGRESAR", todos_path  %>
    

   
  </div>
</div>